linkPrefix = "/SoliditySmartContractRegistry"
name = "SoliditySmartContractRegistry"
version = "1.0.0"
description = "Solidity smart contract registry"
buildTime = 2018-08-26T08:30:12.871Z
target = "doxity"
src = "contracts/*"
dir = "pages/docs"
out = "docs"
author = "Luca Guida"
homepage = "https://lucaguida.github.io/SoliditySmartContractRegistry/"

[interaction]