linkPrefix = "/SolidityExplorer"
name = "SolidityExplorer"
version = "1.0.0"
description = "Library contracts Explorer"
buildTime = 2018-07-22T09:17:51.221Z
target = "doxity"
src = "contracts/*"
dir = "pages/docs"
out = "docs"
author = "Luca Guida"
homepage = "https://lucaguida.github.io/SolidityExplorer/"

[interaction]